GET http://localhost:9000/healthcheck

###

POST http://localhost:9000/api/users/login
Accept: application/json

{
  "user":{
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

###

POST http://localhost:9000/api/users
Accept: application/json

{
  "user": {
    "email": "jake@jake.jake",
    "password": "jakejake",
    "username": "johnjacob"
  }
}

###

GET http://localhost:9000/api/users/
Accept: application/json
Authorization: Token eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImpvaG5qYWNvYiIsImVtYWlsIjoiamFrZUBqYWtlLmpha2UiLCJleHAiOjE1Mzg3MjU2Mzd9.PcQPzDA66tKsP-TqlAIGQrZzZgCa8A1HWrcmEv5a4v8

###

GET http://localhost:9000/api/profiles/johnjacob
Accept: application/json
Authorization: Token eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImpvaG5qYWNvYiIsImVtYWlsIjoiamFrZUBqYWtlLmpha2UiLCJleHAiOjE1Mzg3MjU2Mzd9.PcQPzDA66tKsP-TqlAIGQrZzZgCa8A1HWrcmEv5a4v8

###
